-- Order Rental Processing System Schema
-- Version 1.0
-- Created: 28 Feb 2026

CREATE DATABASE DatabaseDB;
GO

USE DatabaseDB;
GO

--TEAM 1 PRIMARY KEY TABLES

--TEAM 2 PRIMARY KEY TABLES

--TEAM 3 PRIMARY KEY TABLES

--TEAM 4 PRIMARY KEY TABLES
CREATE TABLE IF NOT EXISTS OrderStatusHistory (
  historyId INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  status ENUM('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED') NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedBy VARCHAR(50) NOT NULL,
  remark VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Refund (
  refundId INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  customerId INT NOT NULL,
  depositRefundAmount DECIMAL(10,2) NOT NULL,
  returnDate DATETIME NOT NULL,
  penaltyAmount DECIMAL(10,2) DEFAULT 0.00,
  returnMethod VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Shipment (
  trackingId INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  batchId INT NOT NULL,
  status ENUM('PENDING', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED') NOT NULL,
  weight DOUBLE NOT NULL,
  destination VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS DeliveryMethod (
  deliveryId INT AUTO_INCREMENT PRIMARY KEY,
  orderId INT NOT NULL,
  durationDays INT NOT NULL,
  deliveryCost DECIMAL(10,2) NOT NULL,
  carrierId VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Notification (
  notificationId INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  message VARCHAR(255) NOT NULL,
  dateSent DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isRead BOOL NOT NULL DEFAULT FALSE,
  type ENUM('ORDER_UPDATE', 'PROMOTION', 'SYSTEM', 'PRODUCT') NOT NULL
);

CREATE TABLE IF NOT EXISTS NotificationPreference (
  preferenceId INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  emailEnabled BOOL NOT NULL DEFAULT TRUE,
  smsEnabled BOOL NOT NULL DEFAULT FALSE,
  frequency ENUM('INSTANT', 'DAILY', 'WEEKLY') NOT NULL,
  granularity ENUM('ALL', 'IMPORTANT_ONLY', 'NONE') NOT NULL
);

CREATE TABLE IF NOT EXISTS User (
  userId INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  phoneCountry INT,
  phoneNumber VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS Customer (
  customerId INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  address VARCHAR(255) NOT NULL,
  customerType INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Staff (
  staffId INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  department VARCHAR(50) NOT NULL
);

--TEAM 5 PRIMARY KEY TABLES
--TEAM 5 001_building_footprint table
CREATE TABLE IF NOT EXISTS BuildingFootprint (
  buildingCarbonFootprintID SERIAL PRIMARY KEY,
  timeHourly TIMESTAMP NOT NULL,
  zone VARCHAR(50),
  block VARCHAR(50),
  floor VARCHAR(50),
  room VARCHAR(50),
  totalRoomCo2 DOUBLE PRECISION NOT NULL
);

--TEAM 6 PRIMARY KEY TABLES